#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "latest"
golang = "latest"
node = "latest"
python = "latest"
ruby = "latest"
mago = "latest"
gum = "0.17"
"npm:agent-browser" = "latest"
"npm:ccstatusline" = "latest"
"npm:ctx7" = "latest"
"npm:portless" = "latest"
"npm:vercel" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "python", "golang"]

[hooks]
postinstall = "npx --yes corepack enable"
