#:schema https://mise.jdx.dev/schema/mise.json

[tools]
bun = "1.3"
golang = "1.26"
node = "24"
python = "3.14"
ruby = "4.0"
mago = "latest"
"npm:agent-browser" = "latest"
"npm:ccstatusline" = "latest"
"npm:ctx7" = "latest"
"npm:portless" = "latest"
"npm:vercel" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node", "python", "golang"]

[hooks]
postinstall = "npx corepack enable"