#!/bin/zsh

alias mcat="glow"
alias code=cursor

# Modern replacements for common utils
alias cat=bat
alias df=duf
alias nano=micro
alias ps=procs
alias ls="eza --git --group-directories-first -1"

# Worktrunk shortcuts
alias wts="wt switch"
alias wtx="wt step promote"
alias wtp="wt step prune"
