#!/bin/zsh

export ZFUNCDIR="$HOME/.dotfiles/functions"

export EDITOR="micro"
export VISUAL="cursor -w"
export MICRO_TRUECOLOR=1

export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac

export PATH="$HOME/.local/bin:$PATH"
