#!/bin/zsh

if [[ ! $1 =~ '^[^/]+/[^/]+$' ]]; then
	echo >&2 "usage: clone_repo owner/repo"
	return 1
fi

local dir="$CODE_DIR/$1"
gh repo clone "$1" "$dir" || return
mkdir -p "${dir:h}/.worktrees"
cd "$dir"
