#!/bin/zsh

local dir=${${1:-.}:A}

if [[ $dir != $HOME && $dir != $HOME/* ]]; then
	echo >&2 "only paths under $HOME are shared."
	return 1
fi

local url="smb://workbox/$USER${${dir#$HOME}// /%20}"

print -r -- $'\e]8;;'"$url"$'\e\\'"$url"$'\e]8;;\e\\'
