#!/bin/zsh

export LC_CTYPE=C

mkdir -p /tmp/buildkite-cache /tmp/buildkite-git-mirrors

export BUILDKITE_PLUGIN_FS_CACHE_FOLDER=/tmp/buildkite-cache
export BUILDKITE_GIT_MIRRORS_PATH=/tmp/buildkite-git-mirrors

LC_CTYPE=C buildkite-agent start --spawn=3
