#!/usr/bin/env bash

sudo -v
while true; do
	sudo -n true
	sleep 60
	kill -0 "$$" || exit
done 2>/dev/null &

fancy_echo() {
	local fmt="$1"
	shift
	printf '\n%s\n' "$fmt" "$@"
}

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT
ret=0

set -e

if ! command -v brew >/dev/null; then
	fancy_echo "Installing Homebrew..."
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
	eval "$(/opt/homebrew/bin/brew shellenv)"
fi

fancy_echo "Updating Homebrew formulae..."
brew update
brew bundle

fancy_echo "Installing dotfiles..."
RCRC="$(pwd)/rcrc" rcup

fancy_echo "Installing default language versions..."
mise install

# Homebrew doesn't autoupdate, so install Claude Code manually
fancy_echo "Installing Claude Code..."
curl -fsSL https://claude.ai/install.sh | bash

fancy_echo "Setting macOS defaults..."
./macos

# TODO
# enable terminal to be free from Gatekeeper checks -
# add all terminals to the Developer Tools section
# https://notes.billmill.org/computer_usage/mac_os/Avoiding_gatekeeper_in_your_terminal.html
# sudo spctl developer-mode enable-terminal
