#!/usr/bin/env bash

sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

fancy_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
}

trap 'ret=$?; test $ret -ne 0 && printf "failed\n\n" >&2; exit $ret' EXIT

set -e

if ! command -v brew >/dev/null; then
  fancy_echo "Installing Homebrew..."
  curl -fsS \
    'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby

  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

fancy_echo "Updating Homebrew formulae..."
brew update
brew bundle

fancy_echo "Installing dotfiles..."
RCRC="$(pwd)/rcrc" rcup

asdf_plugins=(golang nodejs python ruby)

for i in "${asdf_plugins[@]}"
do
	if ! asdf plugin-list | grep -q "$i"; then
    fancy_echo "Installing $i..."
    asdf plugin-add "$i"
  fi
done

fancy_echo "Installing default language versions..."
asdf install

fancy_echo "Setting macOS defaults..."
./macos
