#!/bin/zsh

export RCRC="$HOME/.dotfiles/rcrc"
export EDITOR="micro"
export BAT_THEME="Catppuccin Mocha"

export MICRO_TRUECOLOR=1

export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"

export PNPM_HOME="$HOME/Library/pnpm"
case ":$PATH:" in
*":$PNPM_HOME:"*) ;;
*) export PATH="$PNPM_HOME:$PATH" ;;
esac

export PATH="$HOME/.local/bin:$PATH"