#!/bin/zsh

FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

source "$(brew --prefix)/share/antigen/antigen.zsh"

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen apply

eval "$(starship init zsh)"
