tap 'homebrew/command-not-found'
tap 'angusfretwell/tap', trusted: true
tap 'buildkite/buildkite', trusted: true
tap 'ddev/ddev', trusted: true

brew 'chezmoi'
brew 'mas'

# Shell
brew 'antidote'
brew 'starship'
brew 'zsh'

# Utils
brew 'bat'
brew 'coreutils'
brew 'cowsay'
brew 'curl'
brew 'dockutil'
brew 'duf'
brew 'eza'
brew 'ffmpeg'
brew 'fiona'
brew 'fzf'
brew 'glow'
brew 'gnupg'
brew 'gum'
brew 'httpie'
brew 'imagemagick'
brew 'jq'
brew 'micro'
brew 'mkcert'
brew 'nano'
brew 'nss'
brew 'procs'
brew 'pv'
brew 'qsv'
brew 'shfmt'
brew 'tealdeer'
brew 'telnet'
brew 'the_silver_searcher'
brew 'watchman'
brew 'wget'
brew 'yq'
brew 'zoxide'

# Git
brew 'gh'
brew 'git'
brew 'git-absorb'
brew 'git-delta'
brew 'git-lfs'
brew 'worktrunk'

# Tools
brew 'awscli'
brew 'biome'
brew 'bk@3'
brew 'ddev'
brew 'flyctl'
brew 'herdr'
brew 'localstack'
brew 'overmind'
brew 'stripe-cli'
brew 'uv'

# Fonts
cask 'font-blex-mono-nerd-font'
cask 'font-sf-compact'
cask 'font-sf-mono'
cask 'font-sf-pro'

# Applications
cask '1password-cli'
cask '1password'
cask 'chromedriver'
cask 'claude'
cask 'cleanshot'
cask 'cursor'
cask 'figma'
cask 'firefox'
cask 'ghostty'
cask 'google-chrome'
cask 'httpie-desktop'
cask 'linear'
cask 'markdown-preview'
cask 'mattermost'
cask 'opal-composer'
cask 'orbstack'
cask 'proxyman'
cask 'raycast@beta'
cask 'screen-studio'
cask 'sf-symbols'
cask 'signal'
cask 'slack'
cask 'tableplus'
cask 'tailscale-app'
cask 'thebrowsercompany-dia'
cask 'whatsapp'
cask 'zoom'

# Mac App Store applications
mas '1Password for Safari', id: 1_569_813_296
mas 'Bear', id: 1_091_189_122
mas 'Keynote', id: 409_183_694
mas 'Numbers', id: 409_203_825
mas 'Pages', id: 409_201_541
mas 'Pixelmator Pro', id: 1_289_583_905
mas 'Things', id: 904_280_696
mas 'Xcode', id: 497_799_835
